import type { ChromePolicyCategory } from './chrome-user-policies';

/** ChromeOS device settings catalog (기기 설정 tab) — practice data for school.sen.ms.kr. */
export const chromeDevicePolicyCategories: ChromePolicyCategory[] = [
  {
    title: "등록 및 액세스",
    items: [
      { name: "강제 재등록", value: "기기를 완전히 삭제한 다음 강제로 자동 재등록", inheritance: "Google 기본값", options: ["Google 기본값 사용", "기기를 완전히 삭제한 다음 강제로 자동 재등록", "강제 재등록 사용 설정", "강제 재등록 사용 중지"] },
      { name: "제로터치 등록 후 자산 식별자 입력", value: "제로터치 등록을 통해 등록된 기기의 자산 ID 및 위치를 입력하도록 허용 안함", inheritance: "Google 기본값", options: ["Google 기본값 사용", "제로터치 등록을 통해 등록된 기기의 자산 ID 및 위치를 입력하도록 허용 안함", "제로터치 등록을 통해 등록된 기기의 자산 ID 및 위치를 입력하도록 허용"] },
      { name: "파워워시", value: "파워워시가 트리거되도록 허용", inheritance: "로컬 단위로 적용됨", options: ["파워워시가 트리거되도록 허용", "파워워시 허용 안함", "Google 기본값 사용"] },
      { name: "인증 액세스", value: "콘텐츠 보호 사용", inheritance: "Google 기본값", options: ["Google 기본값 사용", "콘텐츠 보호 사용", "인증 액세스 사용 설정", "인증 액세스 사용 중지"] },
      { name: "자체 검사 모드", value: "하위 설정 3개", inheritance: "Google 기본값", options: ["Google 기본값 사용", "하위 설정 3개", "자체 검사 모드 구성"] },
      { name: "사용 중지된 기기 반환 안내", value: "연습용 관리 콘솔(school.sen.ms.kr)에서 관리되는 연습 기기입니다. 실제 학교 기기가 아니며 개인 용도로 사용할 수 없습니다. 연습이 끝나면 school.sen.ms.kr 관리자 안내에 따라 반납하세요.", inheritance: "로컬 단위로 적용됨", options: ["연습용 관리 콘솔(school.sen.ms.kr)에서 관리되는 연습 기기입니다. 실제 학교 기기가 아니며 개인 용도로 사용할 수 없습니다. 연습이 끝나면 school.sen.ms.kr 관리자 안내에 따라 반납하세요.", "맞춤 메시지 사용 중지", "Google 기본값 사용"] },
      { name: "통합된 FIDO 2단계 인증", value: "사용자가 결정하도록 허용", inheritance: "Google 기본값", options: ["Google 기본값 사용", "사용자가 결정하도록 허용", "통합된 FIDO 2단계 인증 강제 사용", "통합된 FIDO 2단계 인증 사용 중지"] },
    ],
  },
  {
    title: "로그인 설정",
    items: [
      { name: "게스트 모드", value: "게스트 모드 사용 안함", inheritance: "로컬 단위로 적용됨", options: ["게스트 모드 사용 안함", "게스트 모드 사용", "Google 기본값 사용"] },
      { name: "로그인 제한", value: "하위 설정 2개", inheritance: "Google 기본값", options: ["Google 기본값 사용", "하위 설정 2개", "로그인 제한 구성"] },
      { name: "도메인 자동완성", value: "하위 설정 2개", inheritance: "Google 기본값", options: ["Google 기본값 사용", "하위 설정 2개", "도메인 자동완성 구성"] },
      { name: "로그인 화면", value: "사용자 이름 및 사진 항상 표시", inheritance: "Google 기본값", options: ["Google 기본값 사용", "사용자 이름 및 사진 항상 표시", "로그인 화면 사용 설정", "로그인 화면 사용 중지"] },
      { name: "로그인 제한 예외 시간", value: "항목 없음", inheritance: "Google 기본값", options: ["Google 기본값 사용", "항목 없음", "로그인 제한 예외 시간 항목 추가"] },
      { name: "기기 제한 일정", value: "항목 없음", inheritance: "Google 기본값", options: ["Google 기본값 사용", "항목 없음", "기기 제한 일정 항목 추가"] },
      { name: "기기 배경화면 이미지", value: "업로드된 파일", inheritance: "로컬 단위로 적용됨", options: ["업로드된 파일", "기본 배경화면 사용", "사용자 결정 허용", "Google 기본값 사용"] },
      { name: "사용자 데이터", value: "로컬 사용자 데이터를 삭제하지 않습니다.", inheritance: "Google 기본값", options: ["Google 기본값 사용", "로컬 사용자 데이터를 삭제하지 않습니다.", "로컬 사용자 데이터를 삭제합니다."] },
      { name: "싱글 사인온(SSO) IdP 리디렉션", value: "기본 Google 로그인 화면으로 사용자 이동", inheritance: "로컬 단위로 적용됨", options: ["기본 Google 로그인 화면으로 사용자 이동", "IdP로 리디렉션", "Google 기본값 사용"] },
      { name: "싱글 사인온(SSO) 쿠키 동작", value: "로그인 시 SAML SSO 쿠키를 사용자 세션으로 전달하지 않음", inheritance: "로컬 단위로 적용됨", options: ["로그인 시 SAML SSO 쿠키를 사용자 세션으로 전달하지 않음", "로그인 시 SAML SSO 쿠키를 사용자 세션으로 전달", "Google 기본값 사용"] },
      { name: "싱글 사인온(SSO) 카메라 권한", value: "Google 기본값", inheritance: "Google 기본값", options: ["Google 기본값 사용", "싱글 사인온(SSO) 카메라 권한 사용 설정", "싱글 사인온(SSO) 카메라 권한 사용 중지", "사용자가 결정하도록 허용"] },
      { name: "SAML IdP 로그인 페이지의 사용자 이름 자동 완성", value: "Google 기본값", inheritance: "Google 기본값", options: ["Google 기본값 사용", "SAML IdP 로그인 페이지의 사용자 이름 자동 완성 사용 설정", "SAML IdP 로그인 페이지의 사용자 이름 자동 완성 사용 중지", "사용자가 결정하도록 허용"] },
      { name: "싱글 사인온(SSO) 클라이언트 인증서", value: "Google 기본값", inheritance: "Google 기본값", options: ["Google 기본값 사용", "싱글 사인온(SSO) 클라이언트 인증서 사용 설정", "싱글 사인온(SSO) 클라이언트 인증서 사용 중지", "사용자가 결정하도록 허용"] },
      { name: "접근성 제어", value: "사용자가 로그인 화면의 접근성 설정을 제어하도록 허용", inheritance: "Google 기본값", options: ["Google 기본값 사용", "사용자가 로그인 화면의 접근성 설정을 제어하도록 허용", "접근성 제어 사용 설정", "접근성 제어 사용 중지"] },
      { name: "로그인 언어", value: "최근 사용자 세션의 언어 사용", inheritance: "Google 기본값", options: ["Google 기본값 사용", "최근 사용자 세션의 언어 사용", "로그인 언어 사용 설정", "로그인 언어 사용 중지"] },
      { name: "로그인 키보드", value: "선택한 항목 없음", inheritance: "Google 기본값", options: ["Google 기본값 사용", "선택한 항목 없음", "로그인 키보드 구성"] },
      { name: "싱글 사인온(SSO) 인증 액세스", value: "Google 기본값", inheritance: "Google 기본값", options: ["Google 기본값 사용", "싱글 사인온(SSO) 인증 액세스 사용 설정", "싱글 사인온(SSO) 인증 액세스 사용 중지", "사용자가 결정하도록 허용"] },
      { name: "로그인 화면의 시스템 정보", value: "사용자가 결정하도록 허용", inheritance: "Google 기본값", options: ["Google 기본값 사용", "사용자가 결정하도록 허용", "로그인 화면의 시스템 정보 강제 사용", "로그인 화면의 시스템 정보 사용 중지"] },
      { name: "로그인 화면의 개인정보 보호 화면", value: "사용자가 결정하도록 허용", inheritance: "Google 기본값", options: ["Google 기본값 사용", "사용자가 결정하도록 허용", "로그인 화면의 개인정보 보호 화면 강제 사용", "로그인 화면의 개인정보 보호 화면 사용 중지"] },
      { name: "비밀번호 입력 시 숫자 키보드 표시", value: "비밀번호 입력 시 표준 키보드로 기본 설정", inheritance: "Google 기본값", options: ["Google 기본값 사용", "비밀번호 입력 시 표준 키보드로 기본 설정", "비밀번호 입력 시 숫자 키보드 표시 사용 설정", "비밀번호 입력 시 숫자 키보드 표시 사용 중지"] },
      { name: "로그인/잠금 화면의 차단된 URL", value: "Google 기본값", inheritance: "Google 기본값", options: ["Google 기본값 사용", "로그인/잠금 화면의 차단된 URL 사용 설정", "로그인/잠금 화면의 차단된 URL 사용 중지", "사용자가 결정하도록 허용"] },
      { name: "로그인/잠금 화면의 차단된 URL 예외 항목", value: "Google 기본값", inheritance: "Google 기본값", options: ["Google 기본값 사용", "로그인/잠금 화면의 차단된 URL 예외 항목 사용 설정", "로그인/잠금 화면의 차단된 URL 예외 항목 사용 중지", "사용자가 결정하도록 허용"] },
      { name: "로그인 화면의 WebUSB API 허용 기기", value: "항목 없음", inheritance: "Google 기본값", options: ["Google 기본값 사용", "항목 없음", "로그인 화면의 WebUSB API 허용 기기 항목 추가"] },
      { name: "로그인 화면의 WebHID API 허용 기기", value: "항목 없음", inheritance: "Google 기본값", options: ["Google 기본값 사용", "항목 없음", "로그인 화면의 WebHID API 허용 기기 항목 추가"] },
      { name: "Enterprise 원격 액세스 연결", value: "엔터프라이즈 관리자의 원격 액세스 연결 사용 설정", inheritance: "Google 기본값", options: ["Google 기본값 사용", "엔터프라이즈 관리자의 원격 액세스 연결 사용 설정", "Enterprise 원격 액세스 연결 사용 설정", "Enterprise 원격 액세스 연결 사용 중지"] },
      { name: "온라인 로그인/잠금 화면 자동 새로고침", value: "Google 기본값", inheritance: "Google 기본값", options: ["Google 기본값 사용", "온라인 로그인/잠금 화면 자동 새로고침 사용 설정", "온라인 로그인/잠금 화면 자동 새로고침 사용 중지", "사용자가 결정하도록 허용"] },
    ],
  },
  {
    title: "로그인 화면 접근성",
    items: [
      { name: "음성 확인", value: "사용자가 결정하도록 허용", inheritance: "Google 기본값", options: ["Google 기본값 사용", "사용자가 결정하도록 허용", "음성 확인 강제 사용", "음성 확인 사용 중지"] },
      { name: "텍스트 읽어주기", value: "사용자가 결정하도록 허용", inheritance: "Google 기본값", options: ["Google 기본값 사용", "사용자가 결정하도록 허용", "텍스트 읽어주기 강제 사용", "텍스트 읽어주기 사용 중지"] },
      { name: "고대비", value: "사용자가 결정하도록 허용", inheritance: "Google 기본값", options: ["Google 기본값 사용", "사용자가 결정하도록 허용", "고대비 강제 사용", "고대비 사용 중지"] },
      { name: "화면 돋보기", value: "사용자가 결정하도록 허용", inheritance: "Google 기본값", options: ["Google 기본값 사용", "사용자가 결정하도록 허용", "화면 돋보기 강제 사용", "화면 돋보기 사용 중지"] },
      { name: "고정키", value: "사용자가 결정하도록 허용", inheritance: "Google 기본값", options: ["Google 기본값 사용", "사용자가 결정하도록 허용", "고정키 강제 사용", "고정키 사용 중지"] },
      { name: "터치 키보드", value: "사용자가 결정하도록 허용", inheritance: "Google 기본값", options: ["Google 기본값 사용", "사용자가 결정하도록 허용", "터치 키보드 강제 사용", "터치 키보드 사용 중지"] },
      { name: "음성기록", value: "사용자가 결정하도록 허용", inheritance: "Google 기본값", options: ["Google 기본값 사용", "사용자가 결정하도록 허용", "음성기록 강제 사용", "음성기록 사용 중지"] },
      { name: "키보드 포커스 강조표시", value: "사용자가 결정하도록 허용", inheritance: "Google 기본값", options: ["Google 기본값 사용", "사용자가 결정하도록 허용", "키보드 포커스 강조표시 강제 사용", "키보드 포커스 강조표시 사용 중지"] },
      { name: "캐럿 강조표시", value: "사용자가 결정하도록 허용", inheritance: "Google 기본값", options: ["Google 기본값 사용", "사용자가 결정하도록 허용", "캐럿 강조표시 강제 사용", "캐럿 강조표시 사용 중지"] },
      { name: "자동 클릭 사용 설정됨", value: "사용자가 결정하도록 허용", inheritance: "Google 기본값", options: ["Google 기본값 사용", "사용자가 결정하도록 허용", "자동 클릭 사용 설정됨 강제 사용", "자동 클릭 사용 설정됨 사용 중지"] },
      { name: "큰 커서", value: "사용자가 결정하도록 허용", inheritance: "Google 기본값", options: ["Google 기본값 사용", "사용자가 결정하도록 허용", "큰 커서 강제 사용", "큰 커서 사용 중지"] },
      { name: "커서 강조표시", value: "사용자가 결정하도록 허용", inheritance: "Google 기본값", options: ["Google 기본값 사용", "사용자가 결정하도록 허용", "커서 강조표시 강제 사용", "커서 강조표시 사용 중지"] },
      { name: "기본 마우스 버튼", value: "사용자가 결정하도록 허용", inheritance: "Google 기본값", options: ["Google 기본값 사용", "사용자가 결정하도록 허용", "기본 마우스 버튼 강제 사용", "기본 마우스 버튼 사용 중지"] },
      { name: "모노 오디오", value: "사용자가 결정하도록 허용", inheritance: "Google 기본값", options: ["Google 기본값 사용", "사용자가 결정하도록 허용", "모노 오디오 강제 사용", "모노 오디오 사용 중지"] },
      { name: "접근성 단축키", value: "사용자가 결정하도록 허용", inheritance: "Google 기본값", options: ["Google 기본값 사용", "사용자가 결정하도록 허용", "접근성 단축키 강제 사용", "접근성 단축키 사용 중지"] },
      { name: "페이스 컨트롤", value: "사용자가 결정하도록 허용", inheritance: "Google 기본값", options: ["Google 기본값 사용", "사용자가 결정하도록 허용", "페이스 컨트롤 강제 사용", "페이스 컨트롤 사용 중지"] },
    ],
  },
  {
    title: "기기 업데이트 설정",
    items: [
      { name: "자동 업데이트 설정", value: "하위 설정 12개", inheritance: "Google 기본값", options: ["Google 기본값 사용", "하위 설정 12개", "자동 업데이트 설정 구성"] },
      { name: "연장된 자동 업데이트", value: "연장된 자동 업데이트 기간 동안 업데이트 허용 안함", inheritance: "Google 기본값", options: ["Google 기본값 사용", "연장된 자동 업데이트 기간 동안 업데이트 허용 안함", "연장된 자동 업데이트 기간 동안 업데이트 허용"] },
      { name: "앱 관리 업데이트", value: "nnckehldicaciogcbchegobnafnjkcne", inheritance: "로컬 단위로 적용됨", options: ["nnckehldicaciogcbchegobnafnjkcne", "앱 관리 업데이트 사용 중지", "Google 기본값 사용"] },
      { name: "키오스크 관리 업데이트", value: "키오스크 앱에서 OS 버전을 제어하도록 허용 안함", inheritance: "Google 기본값", options: ["Google 기본값 사용", "키오스크 앱에서 OS 버전을 제어하도록 허용 안함", "키오스크 앱에서 OS 버전을 제어하도록 허용"] },
      { name: "변형", value: "Chrome 변형 사용 설정", inheritance: "Google 기본값", options: ["Google 기본값 사용", "Chrome 변형 사용 설정", "변형 사용 설정", "변형 사용 중지"] },
    ],
  },
  {
    title: "키오스크 설정",
    items: [
      { name: "키오스크 기기 상태 알림 전송", value: "선택한 항목 없음", inheritance: "Google 기본값", options: ["Google 기본값 사용", "선택한 항목 없음", "키오스크 기기 상태 알림 전송 구성"] },
      { name: "키오스크 기기 상태 알림 연락처 정보", value: "하위 설정 2개", inheritance: "Google 기본값", options: ["Google 기본값 사용", "하위 설정 2개", "키오스크 기기 상태 알림 연락처 정보 구성"] },
      { name: "URL 차단", value: "하위 설정 2개", inheritance: "Google 기본값", options: ["Google 기본값 사용", "하위 설정 2개", "URL 차단 구성"] },
      { name: "키오스크 가상 키보드 기능(웹사이트만 해당)", value: "선택한 항목 없음", inheritance: "Google 기본값", options: ["Google 기본값 사용", "선택한 항목 없음", "키오스크 가상 키보드 기능(웹사이트만 해당) 구성"] },
      { name: "키오스크에서 허용되는 입력 방법", value: "Korean", inheritance: "로컬 단위로 적용됨", options: ["Korean", "English (US)", "선택한 항목 없음", "Google 기본값 사용"] },
      { name: "키오스크 문제 해결 도구", value: "문제 해결 도구 사용 중지", inheritance: "Google 기본값", options: ["Google 기본값 사용", "문제 해결 도구 사용 중지", "문제 해결 도구 사용 설정"] },
      { name: "WebUSB API 허용 기기", value: "항목 없음", inheritance: "Google 기본값", options: ["Google 기본값 사용", "항목 없음", "WebUSB API 허용 기기 항목 추가"] },
      { name: "URL로 입력되며 익명으로 처리되는 데이터 수집", value: "키오스크 세션에 대해 URL로 입력되며 익명으로 처리되는 데이터 전송", inheritance: "Google 기본값", options: ["Google 기본값 사용", "키오스크 세션에 대해 URL로 입력되며 익명으로 처리되는 데이터 전송", "URL로 입력되며 익명으로 처리되는 데이터 수집 사용 설정", "URL로 입력되며 익명으로 처리되는 데이터 수집 사용 중지"] },
      { name: "원격 액세스 관리자가 호스트와 파일 전송을 할 수 있도록 허용합니다.", value: "Chrome 원격 데스크톱 파일 전송 사용 중지", inheritance: "Google 기본값", options: ["Google 기본값 사용", "Chrome 원격 데스크톱 파일 전송 사용 중지", "Chrome 원격 데스크톱 파일 전송 사용 설정"] },
      { name: "Enterprise Hardware Platform API", value: "관리되는 확장 프로그램에서 Enterprise Hardware Platform API를 사용하도록 허용 안함", inheritance: "Google 기본값", options: ["Google 기본값 사용", "관리되는 확장 프로그램에서 Enterprise Hardware Platform API를 사용하도록 허용 안함", "관리되는 확장 프로그램에서 Enterprise Hardware Platform API를 사용하도록 허용"] },
      { name: "Web Serial API 허용 기기", value: "항목 없음", inheritance: "Google 기본값", options: ["Google 기본값 사용", "항목 없음", "Web Serial API 허용 기기 항목 추가"] },
      { name: "키오스크 모드에서 허용되는 Chrome 앱", value: "기본 동작 사용", inheritance: "Google 기본값", options: ["Google 기본값 사용", "기본 동작 사용", "키오스크 모드에서 허용되는 Chrome 앱 사용 설정", "키오스크 모드에서 허용되는 Chrome 앱 사용 중지"] },
      { name: "설치된 CA 인증서 관리", value: "모든 인증서 관리 허용", inheritance: "Google 기본값", options: ["Google 기본값 사용", "모든 인증서 관리 허용", "설치된 CA 인증서 관리 사용 설정", "설치된 CA 인증서 관리 사용 중지"] },
      { name: "설치된 클라이언트 인증서 관리", value: "모든 인증서 관리 허용", inheritance: "Google 기본값", options: ["Google 기본값 사용", "모든 인증서 관리 허용", "설치된 클라이언트 인증서 관리 사용 설정", "설치된 클라이언트 인증서 관리 사용 중지"] },
      { name: "자동 인쇄", value: "자동 인쇄 사용 중지", inheritance: "Google 기본값", options: ["Google 기본값 사용", "자동 인쇄 사용 중지", "자동 인쇄 사용 설정"] },
      { name: "키오스크 애플리케이션 수준 로그 수집", value: "키오스크 애플리케이션 수준 로그 수집 사용 중지", inheritance: "Google 기본값", options: ["Google 기본값 사용", "키오스크 애플리케이션 수준 로그 수집 사용 중지", "키오스크 애플리케이션 수준 로그 수집 사용 설정"] },
      { name: "손가락을 모으거나 펼쳐 확대/축소", value: "손가락을 모으거나 펼쳐 확대/축소 허용", inheritance: "Google 기본값", options: ["Google 기본값 사용", "손가락을 모으거나 펼쳐 확대/축소 허용", "손가락을 모으거나 펼쳐 확대/축소 사용 설정", "손가락을 모으거나 펼쳐 확대/축소 사용 중지"] },
    ],
  },
  {
    title: "키오스크 전원 설정",
    items: [
      { name: "덮개를 덮을 때 수행할 작업", value: "절전 모드", inheritance: "Google 기본값", options: ["Google 기본값 사용", "절전 모드", "덮개를 덮을 때 수행할 작업 사용 설정", "덮개를 덮을 때 수행할 작업 사용 중지"] },
      { name: "AC 키오스크 전원 설정", value: "하위 설정 5개", inheritance: "Google 기본값", options: ["Google 기본값 사용", "하위 설정 5개", "AC 키오스크 전원 설정 구성"] },
      { name: "배터리 키오스크 전원 설정", value: "하위 설정 5개", inheritance: "Google 기본값", options: ["Google 기본값 사용", "하위 설정 5개", "배터리 키오스크 전원 설정 구성"] },
      { name: "기기 절전 모드", value: "하위 설정 2개", inheritance: "Google 기본값", options: ["Google 기본값 사용", "하위 설정 2개", "기기 절전 모드 구성"] },
    ],
  },
  {
    title: "키오스크 접근성",
    items: [
      { name: "키오스크 플로팅 접근성 메뉴", value: "키오스크 모드에서 플로팅 접근성 메뉴 표시 안함", inheritance: "Google 기본값", options: ["Google 기본값 사용", "키오스크 모드에서 플로팅 접근성 메뉴 표시 안함", "키오스크 모드에서 플로팅 접근성 메뉴 표시"] },
      { name: "키오스크 음성 피드백", value: "사용자가 결정하도록 허용", inheritance: "Google 기본값", options: ["Google 기본값 사용", "사용자가 결정하도록 허용", "키오스크 음성 피드백 강제 사용", "키오스크 음성 피드백 사용 중지"] },
      { name: "키오스크 텍스트 읽어주기", value: "사용자가 결정하도록 허용", inheritance: "Google 기본값", options: ["Google 기본값 사용", "사용자가 결정하도록 허용", "키오스크 텍스트 읽어주기 강제 사용", "키오스크 텍스트 읽어주기 사용 중지"] },
      { name: "키오스크 고대비", value: "사용자가 결정하도록 허용", inheritance: "Google 기본값", options: ["Google 기본값 사용", "사용자가 결정하도록 허용", "키오스크 고대비 강제 사용", "키오스크 고대비 사용 중지"] },
      { name: "키오스크 고정키", value: "사용자가 결정하도록 허용", inheritance: "Google 기본값", options: ["Google 기본값 사용", "사용자가 결정하도록 허용", "키오스크 고정키 강제 사용", "키오스크 고정키 사용 중지"] },
      { name: "키오스크 터치 키보드", value: "사용자가 결정하도록 허용", inheritance: "Google 기본값", options: ["Google 기본값 사용", "사용자가 결정하도록 허용", "키오스크 터치 키보드 강제 사용", "키오스크 터치 키보드 사용 중지"] },
      { name: "키오스크 음성기록", value: "사용자가 결정하도록 허용", inheritance: "Google 기본값", options: ["Google 기본값 사용", "사용자가 결정하도록 허용", "키오스크 음성기록 강제 사용", "키오스크 음성기록 사용 중지"] },
      { name: "키오스크 키보드 포커스 강조표시", value: "사용자가 결정하도록 허용", inheritance: "Google 기본값", options: ["Google 기본값 사용", "사용자가 결정하도록 허용", "키오스크 키보드 포커스 강조표시 강제 사용", "키오스크 키보드 포커스 강조표시 사용 중지"] },
      { name: "키오스크 캐럿 강조표시", value: "사용자가 결정하도록 허용", inheritance: "Google 기본값", options: ["Google 기본값 사용", "사용자가 결정하도록 허용", "키오스크 캐럿 강조표시 강제 사용", "키오스크 캐럿 강조표시 사용 중지"] },
      { name: "키오스크 자동 클릭이 사용 설정됨", value: "사용자가 결정하도록 허용", inheritance: "Google 기본값", options: ["Google 기본값 사용", "사용자가 결정하도록 허용", "키오스크 자동 클릭이 사용 설정됨 강제 사용", "키오스크 자동 클릭이 사용 설정됨 사용 중지"] },
      { name: "키오스크 큰 커서", value: "사용자가 결정하도록 허용", inheritance: "Google 기본값", options: ["Google 기본값 사용", "사용자가 결정하도록 허용", "키오스크 큰 커서 강제 사용", "키오스크 큰 커서 사용 중지"] },
      { name: "키오스크 커서 강조표시", value: "사용자가 결정하도록 허용", inheritance: "Google 기본값", options: ["Google 기본값 사용", "사용자가 결정하도록 허용", "키오스크 커서 강조표시 강제 사용", "키오스크 커서 강조표시 사용 중지"] },
      { name: "키오스크 기본 마우스 버튼", value: "사용자가 결정하도록 허용", inheritance: "Google 기본값", options: ["Google 기본값 사용", "사용자가 결정하도록 허용", "키오스크 기본 마우스 버튼 강제 사용", "키오스크 기본 마우스 버튼 사용 중지"] },
      { name: "키오스크 모노 오디오", value: "사용자가 결정하도록 허용", inheritance: "Google 기본값", options: ["Google 기본값 사용", "사용자가 결정하도록 허용", "키오스크 모노 오디오 강제 사용", "키오스크 모노 오디오 사용 중지"] },
      { name: "키오스크 접근성 단축키", value: "사용자가 결정하도록 허용", inheritance: "Google 기본값", options: ["Google 기본값 사용", "사용자가 결정하도록 허용", "키오스크 접근성 단축키 강제 사용", "키오스크 접근성 단축키 사용 중지"] },
      { name: "키오스크 화면 돋보기", value: "사용자가 결정하도록 허용", inheritance: "Google 기본값", options: ["Google 기본값 사용", "사용자가 결정하도록 허용", "키오스크 화면 돋보기 강제 사용", "키오스크 화면 돋보기 사용 중지"] },
    ],
  },
  {
    title: "사용자 및 기기 보고",
    items: [
      { name: "기기 OS 정보 보고", value: "하위 설정 2개", inheritance: "Google 기본값", options: ["Google 기본값 사용", "하위 설정 2개", "기기 OS 정보 보고 구성"] },
      { name: "기기 하드웨어 정보 보고", value: "하위 설정 2개", inheritance: "Google 기본값", options: ["Google 기본값 사용", "하위 설정 2개", "기기 하드웨어 정보 보고 구성"] },
      { name: "기기 텔레메트리 보고", value: "하위 설정 2개", inheritance: "Google 기본값", options: ["Google 기본값 사용", "하위 설정 2개", "기기 텔레메트리 보고 구성"] },
      { name: "기기 사용자 추적 보고", value: "최근 사용자 추적 기능 사용 설정", inheritance: "Google 기본값", options: ["Google 기본값 사용", "최근 사용자 추적 기능 사용 설정", "기기 사용자 추적 보고 사용 설정", "기기 사용자 추적 보고 사용 중지"] },
      { name: "키오스크 세션 상태 보고", value: "키오스크 세션 상태 보고 사용 설정", inheritance: "Google 기본값", options: ["Google 기본값 사용", "키오스크 세션 상태 보고 사용 설정", "키오스크 세션 상태 보고 사용 설정", "키오스크 세션 상태 보고 사용 중지"] },
      { name: "실행 중인 키오스크 앱 보고", value: "실행 중인 키오스크 앱 보고 사용 중지", inheritance: "Google 기본값", options: ["Google 기본값 사용", "실행 중인 키오스크 앱 보고 사용 중지", "실행 중인 키오스크 앱 보고 사용 설정"] },
      { name: "기기 인쇄 작업 보고", value: "인쇄 작업 보고 사용 중지", inheritance: "Google 기본값", options: ["Google 기본값 사용", "인쇄 작업 보고 사용 중지", "인쇄 작업 보고 사용 설정"] },
      { name: "기기 상태 보고서 업로드 빈도", value: "180분", inheritance: "Google 기본값", options: ["Google 기본값 사용", "180분", "기기 상태 보고서 업로드 빈도 사용 설정", "기기 상태 보고서 업로드 빈도 사용 중지"] },
      { name: "비활성 기기 알림", value: "하위 설정 4개", inheritance: "Google 기본값", options: ["Google 기본값 사용", "하위 설정 4개", "비활성 기기 알림 구성"] },
      { name: "통계 보고", value: "통계를 항상 Google에 보내기", inheritance: "Google 기본값", options: ["Google 기본값 사용", "통계를 항상 Google에 보내기", "통계 보고 사용 설정", "통계 보고 사용 중지"] },
      { name: "기기 시스템 로그 업로드", value: "기기 시스템 로그 업로드 사용 안함", inheritance: "Google 기본값", options: ["Google 기본값 사용", "기기 시스템 로그 업로드 사용 안함", "기기 시스템 로그 업로드 사용"] },
      { name: "시스템 전체의 성능 흔적 수집", value: "사용자가 시스템 전체의 성능 흔적을 수집하지 못하도록 차단", inheritance: "Google 기본값", options: ["Google 기본값 사용", "사용자가 시스템 전체의 성능 흔적을 수집하지 못하도록 차단", "사용자가 시스템 전체의 성능 흔적을 수집하지 못하도록 허용"] },
      { name: "확장 감지 및 반응(XDR) 이벤트 보고", value: "확장 감지 및 반응(XDR) 이벤트와 관련된 정보 보고 안함", inheritance: "Google 기본값", options: ["Google 기본값 사용", "확장 감지 및 반응(XDR) 이벤트와 관련된 정보 보고 안함", "확장 감지 및 반응(XDR) 이벤트 보고 사용 설정", "확장 감지 및 반응(XDR) 이벤트 보고 사용 중지"] },
      { name: "확장 프로그램 시스템 로깅", value: "기업 확장 프로그램 시스템 로깅 사용 중지", inheritance: "Google 기본값", options: ["Google 기본값 사용", "기업 확장 프로그램 시스템 로깅 사용 중지", "기업 확장 프로그램 시스템 로깅 사용 설정"] },
    ],
  },
  {
    title: "표시 설정",
    items: [
      { name: "화면 설정", value: "하위 설정 6개", inheritance: "Google 기본값", options: ["Google 기본값 사용", "하위 설정 6개", "화면 설정 구성"] },
    ],
  },
  {
    title: "전원 및 종료",
    items: [
      { name: "전원 관리", value: "로그인 화면에서 유휴 상태일 때 기기가 절전 모드로 전환되거나 종료되는 것을 허용합니다.", inheritance: "Google 기본값", options: ["Google 기본값 사용", "로그인 화면에서 유휴 상태일 때 기기가 절전 모드로 전환되거나 종료되는 것을 허용합니다.", "전원 관리 사용 설정", "전원 관리 사용 중지"] },
      { name: "가동시간 한도 이후 재부팅", value: "Google 기본값", inheritance: "Google 기본값", options: ["Google 기본값 사용", "가동시간 한도 이후 재부팅 사용 설정", "가동시간 한도 이후 재부팅 사용 중지", "사용자가 결정하도록 허용"] },
      { name: "종료 허용", value: "사용자가 종료 아이콘 또는 기기의 전원 버튼을 사용하여 기기를 끌 수 있도록 허용", inheritance: "Google 기본값", options: ["Google 기본값 사용", "사용자가 종료 아이콘 또는 기기의 전원 버튼을 사용하여 기기를 끌 수 있도록 허용", "종료 허용 사용 설정", "종료 허용 사용 중지"] },
      { name: "배터리 충전 최적화", value: "사용자가 결정하도록 허용", inheritance: "Google 기본값", options: ["Google 기본값 사용", "사용자가 결정하도록 허용", "배터리 충전 최적화 강제 사용", "배터리 충전 최적화 사용 중지"] },
      { name: "로그아웃 시 재부팅", value: "사용자 로그아웃 시 재부팅하지 않음", inheritance: "Google 기본값", options: ["Google 기본값 사용", "사용자 로그아웃 시 재부팅하지 않음", "사용자 로그아웃 시 재부팅"] },
      { name: "예약된 재부팅", value: "하위 설정 5개", inheritance: "Google 기본값", options: ["Google 기본값 사용", "하위 설정 5개", "예약된 재부팅 구성"] },
      { name: "화면 보호기", value: "하위 설정 4개", inheritance: "Google 기본값", options: ["Google 기본값 사용", "하위 설정 4개", "화면 보호기 구성"] },
    ],
  },
  {
    title: "가상 머신",
    items: [
      { name: "독립적인 사용자용 Linux 가상 머신", value: "독립적인 사용자용 Linux 앱을 지원하는 데 필요한 가상 머신의 사용 허용", inheritance: "로컬 단위로 적용됨", options: ["독립적인 사용자용 Linux 앱을 지원하는 데 필요한 가상 머신의 사용 허용", "Linux 가상 머신 사용 허용 안함", "Google 기본값 사용"] },
      { name: "신뢰할 수 없는 소스의 Android 앱", value: "기기의 사용자가 ADB를 사용하여 사이드로드하는 것을 차단", inheritance: "Google 기본값", options: ["Google 기본값 사용", "기기의 사용자가 ADB를 사용하여 사이드로드하는 것을 차단", "기기의 사용자가 ADB를 사용하여 사이드로드하는 것을 허용"] },
    ],
  },
  {
    title: "기타 설정",
    items: [
      { name: "기기 네트워크 호스트 이름 템플릿", value: "Google 기본값", inheritance: "Google 기본값", options: ["Google 기본값 사용", "기기 네트워크 호스트 이름 템플릿 사용 설정", "기기 네트워크 호스트 이름 템플릿 사용 중지", "사용자가 결정하도록 허용"] },
      { name: "인터넷 인쇄 프로토콜 클라이언트 이름 속성", value: "Google 기본값", inheritance: "Google 기본값", options: ["Google 기본값 사용", "인터넷 인쇄 프로토콜 클라이언트 이름 속성 사용 설정", "인터넷 인쇄 프로토콜 클라이언트 이름 속성 사용 중지", "사용자가 결정하도록 허용"] },
      { name: "시간대", value: "하위 설정 2개", inheritance: "Google 기본값", options: ["Google 기본값 사용", "하위 설정 2개", "시간대 구성"] },
      { name: "모바일 데이터 로밍", value: "모바일 데이터 로밍 허용 안함", inheritance: "Google 기본값", options: ["Google 기본값 사용", "모바일 데이터 로밍 허용 안함", "모바일 데이터 로밍 허용"] },
      { name: "USB 액세스", value: "Google 기본값", inheritance: "Google 기본값", options: ["Google 기본값 사용", "USB 액세스 사용 설정", "USB 액세스 사용 중지", "사용자가 결정하도록 허용"] },
      { name: "주변기기 데이터 액세스 보호", value: "사용자가 결정하도록 허용", inheritance: "Google 기본값", options: ["Google 기본값 사용", "사용자가 결정하도록 허용", "주변기기 데이터 액세스 보호 강제 사용", "주변기기 데이터 액세스 보호 사용 중지"] },
      { name: "블루투스", value: "블루투스 사용 중지 안함", inheritance: "Google 기본값", options: ["Google 기본값 사용", "블루투스 사용 중지 안함", "블루투스 사용 설정 안함"] },
      { name: "블루투스 서비스가 허용됨", value: "Google 기본값", inheritance: "Google 기본값", options: ["Google 기본값 사용", "블루투스 서비스가 허용됨 사용 설정", "블루투스 서비스가 허용됨 사용 중지", "사용자가 결정하도록 허용"] },
      { name: "'Just Works' 블루투스 페어링", value: "'Just Works' 블루투스 페어링 요청 거부", inheritance: "Google 기본값", options: ["Google 기본값 사용", "'Just Works' 블루투스 페어링 요청 거부", "'Just Works' 블루투스 페어링 요청 허용"] },
      { name: "기기 대역폭 조절", value: "하위 설정 3개", inheritance: "Google 기본값", options: ["Google 기본값 사용", "하위 설정 3개", "기기 대역폭 조절 구성"] },
      { name: "펌웨어 업데이트", value: "하위 설정 2개", inheritance: "Google 기본값", options: ["Google 기본값 사용", "하위 설정 2개", "펌웨어 업데이트 구성"] },
      { name: "TPM 펌웨어 업데이트", value: "사용자가 TPM 펌웨어 업데이트를 수행하지 못하도록 차단", inheritance: "Google 기본값", options: ["Google 기본값 사용", "사용자가 TPM 펌웨어 업데이트를 수행하지 못하도록 차단", "사용자가 TPM 펌웨어 업데이트를 수행하지 못하도록 허용"] },
      { name: "인증된 프록시 트래픽", value: "하위 설정 3개", inheritance: "Google 기본값", options: ["Google 기본값 사용", "하위 설정 3개", "인증된 프록시 트래픽 구성"] },
      { name: "시스템 시간 형식", value: "현재 언어를 기준으로 자동 설정됨", inheritance: "Google 기본값", options: ["Google 기본값 사용", "현재 언어를 기준으로 자동 설정됨", "시스템 시간 형식 사용 설정", "시스템 시간 형식 사용 중지"] },
      { name: "앱 및 확장 프로그램 캐시 크기", value: "Google 기본값", inheritance: "Google 기본값", options: ["Google 기본값 사용", "앱 및 확장 프로그램 캐시 크기 사용 설정", "앱 및 확장 프로그램 캐시 크기 사용 중지", "사용자가 결정하도록 허용"] },
      { name: "하드웨어 프로필", value: "Google 서버에서 하드웨어 프로필 다운로드 허용", inheritance: "Google 기본값", options: ["Google 기본값 사용", "Google 서버에서 하드웨어 프로필 다운로드 허용", "하드웨어 프로필 사용 설정", "하드웨어 프로필 사용 중지"] },
      { name: "디스크 공간 부족 알림", value: "디스크 공간 부족 시 알림 표시 안함", inheritance: "Google 기본값", options: ["Google 기본값 사용", "디스크 공간 부족 시 알림 표시 안함", "디스크 공간 부족 시 알림 표시"] },
      { name: "Chrome OS 등록을 통한 혜택 사용", value: "사용자가 Chrome OS 등록을 통해 쿠폰을 사용하도록 허용", inheritance: "Google 기본값", options: ["Google 기본값 사용", "사용자가 Chrome OS 등록을 통해 쿠폰을 사용하도록 허용", "Chrome OS 등록을 통한 혜택 사용 사용 설정", "Chrome OS 등록을 통한 혜택 사용 사용 중지"] },
      { name: "네트워크 패킷 캡처 디버그", value: "사용자가 네트워크 패킷 캡처를 수행하도록 허용", inheritance: "Google 기본값", options: ["Google 기본값 사용", "사용자가 네트워크 패킷 캡처를 수행하도록 허용", "네트워크 패킷 캡처 디버그 사용 설정", "네트워크 패킷 캡처 디버그 사용 중지"] },
      { name: "여러 인증서가 일치하는 경우 로그인 화면에 메시지 표시", value: "사용자에게 클라이언트 인증서를 선택하라는 메시지를 로그인 화면에 표시하지 않음", inheritance: "Google 기본값", options: ["Google 기본값 사용", "사용자에게 클라이언트 인증서를 선택하라는 메시지를 로그인 화면에 표시하지 않음", "여러 인증서가 일치하는 경우 로그인 화면에 메시지 표시 사용 설정", "여러 인증서가 일치하는 경우 로그인 화면에 메시지 표시 사용 중지"] },
      { name: "키 보관함 사용 설정", value: "사용자 스토리지 암호화를 위해 암호화 알고리즘이 포함된 키 보관함 사용 안함", inheritance: "Google 기본값", options: ["Google 기본값 사용", "사용자 스토리지 암호화를 위해 암호화 알고리즘이 포함된 키 보관함 사용 안함", "사용자 스토리지 암호화를 위해 암호화 알고리즘이 포함된 키 보관함 사용"] },
      { name: "국제 키보드 단축키 매핑", value: "국제 키보드 단축키가 키보드의 키 위치에 매핑됨", inheritance: "Google 기본값", options: ["Google 기본값 사용", "국제 키보드 단축키가 키보드의 키 위치에 매핑됨", "국제 키보드 단축키 매핑 사용 설정", "국제 키보드 단축키 매핑 사용 중지"] },
      { name: "독립적인 사용자용 Android 앱", value: "독립적인 사용자가 Android 앱을 사용하도록 허용", inheritance: "Google 기본값", options: ["Google 기본값 사용", "독립적인 사용자가 Android 앱을 사용하도록 허용", "독립적인 사용자용 Android 앱 사용 설정", "독립적인 사용자용 Android 앱 사용 중지"] },
      { name: "키보드 백라이트 색상: 기본", value: "배경화면", inheritance: "Google 기본값", options: ["Google 기본값 사용", "배경화면", "키보드 백라이트 색상: 기본 사용 설정", "키보드 백라이트 색상: 기본 사용 중지"] },
      { name: "배터리 잔량 낮음 알림음", value: "사용자가 결정하도록 허용", inheritance: "Google 기본값", options: ["Google 기본값 사용", "사용자가 결정하도록 허용", "배터리 잔량 낮음 알림음 강제 사용", "배터리 잔량 낮음 알림음 사용 중지"] },
      { name: "충전음", value: "사용자가 결정하도록 허용", inheritance: "Google 기본값", options: ["Google 기본값 사용", "사용자가 결정하도록 허용", "충전음 강제 사용", "충전음 사용 중지"] },
      { name: "주변기기 드라이버 미리 로드", value: "선택한 항목 없음", inheritance: "Google 기본값", options: ["Google 기본값 사용", "선택한 항목 없음", "주변기기 드라이버 미리 로드 구성"] },
      { name: "ChromeOS Flex의 추가 하드웨어 데이터", value: "ChromeOS Flex에서 추가 하드웨어 데이터 전송", inheritance: "Google 기본값", options: ["Google 기본값 사용", "ChromeOS Flex에서 추가 하드웨어 데이터 전송", "ChromeOS Flex의 추가 하드웨어 데이터 사용 설정", "ChromeOS Flex의 추가 하드웨어 데이터 사용 중지"] },
      { name: "ChromeOS Flex에 ArcVM 이미지 미리 로드", value: "ArcVM 이미지 미리 로드 사용 중지", inheritance: "Google 기본값", options: ["Google 기본값 사용", "ArcVM 이미지 미리 로드 사용 중지", "ArcVM 이미지 미리 로드 사용 설정"] },
      { name: "하드웨어 동영상 가속", value: "하드웨어 동영상 디코딩 사용 설정", inheritance: "Google 기본값", options: ["Google 기본값 사용", "하드웨어 동영상 디코딩 사용 설정", "하드웨어 동영상 가속 사용 설정", "하드웨어 동영상 가속 사용 중지"] },
      { name: "기능 키 동작", value: "사용자가 결정하도록 허용", inheritance: "Google 기본값", options: ["Google 기본값 사용", "사용자가 결정하도록 허용", "기능 키 동작 강제 사용", "기능 키 동작 사용 중지"] },
    ],
  },
  {
    title: "Imprivata",
    items: [
      { name: "Imprivata 로그인 화면 통합", value: "하위 설정 3개", inheritance: "Google 기본값", options: ["Google 기본값 사용", "하위 설정 3개", "Imprivata 로그인 화면 통합 구성"] },
      { name: "공유 키오스크 모드", value: "공유 키오스크 모드 사용 중지", inheritance: "Google 기본값", options: ["Google 기본값 사용", "공유 키오스크 모드 사용 중지", "공유 키오스크 모드 사용 설정"] },
      { name: "공유 앱 및 확장 프로그램", value: "Google 기본값", inheritance: "Google 기본값", options: ["Google 기본값 사용", "공유 앱 및 확장 프로그램 사용 설정", "공유 앱 및 확장 프로그램 사용 중지", "사용자가 결정하도록 허용"] },
    ],
  },
  {
    title: "보안",
    items: [
      { name: "포스트 퀀텀 TLS", value: "기본 Chrome 설정 사용", inheritance: "Google 기본값", options: ["Google 기본값 사용", "기본 Chrome 설정 사용", "포스트 퀀텀 TLS 사용 설정", "포스트 퀀텀 TLS 사용 중지"] },
      { name: "기기 보안 키 증명", value: "Google 기본값", inheritance: "Google 기본값", options: ["Google 기본값 사용", "기기 보안 키 증명 사용 설정", "기기 보안 키 증명 사용 중지", "사용자가 결정하도록 허용"] },
      { name: "로그인 화면의 TLS 키 교환 알고리즘", value: "기본 키 교환 방법 사용", inheritance: "Google 기본값", options: ["Google 기본값 사용", "기본 키 교환 방법 사용", "로그인 화면의 TLS 키 교환 알고리즘 사용 설정", "로그인 화면의 TLS 키 교환 알고리즘 사용 중지"] },
      { name: "로그인 화면의 TLS 암호화 환경설정", value: "기본 ChromeOS 암호화 순서 사용", inheritance: "Google 기본값", options: ["Google 기본값 사용", "기본 ChromeOS 암호화 순서 사용", "로그인 화면의 TLS 암호화 환경설정 사용 설정", "로그인 화면의 TLS 암호화 환경설정 사용 중지"] },
    ],
  },
];

export const chromeDevicePolicyCount = chromeDevicePolicyCategories.reduce((n, c) => n + c.items.length, 0);

